LineaIII/LineaIII/urls.py
from cgitb import handler
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("centro_educativo.urls")),
]

handler404 = 'centro_educativo.views.not_found_page'

LineaIII/centro_educativo/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

from . import views

app_name = "centro_educativo"
urlpatterns = [
    path("", LoginView.as_view(template_name='centro_educativo/login.html'), name="login"),
    path("home", views.home, name="home"),
    path("courses", views.courses, name="courses"),
    path("studentForm", views.studentForm, name="studentForm"),
    path("editStudent/<int:student_id>", views.editStudent, name="editStudent"),
    path("editRecordStudent", views.editRecordStudent, name="editRecordStudent"),
    path("editCourse/<int:course_id>", views.editCourse, name="editCourse"),
    path("editRecordCourse", views.editRecordCourse, name="editRecordCourse"),
    path("deleteStudent/<int:pk>", views.deleteStudent, name="deleteStudent"),
    path("deleteCourse/<int:pk>", views.deleteCourse, name="deleteCourse"),
    path("logout", LogoutView.as_view(template_name='centro_educativo/login.html'), name="logout"),
    path("addCourseinUser/<int:student_id><int:course_id>", views.addCourseinUser, name="addCourseinUser"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""path("register", views.register, name="register"),"""

LineaIII/centro_educativo/models.py
from django.db import models
from django.contrib.auth.models import User

class Courses(models.Model):
    code = models.CharField(max_length=25)
    name = models.CharField(max_length=30)
    credits = models.BigIntegerField()

    def __str__(self):
        return self.name

class Students(models.Model):
    code = models.CharField(max_length=25)
    name = models.CharField(max_length=25)
    lastName = models.CharField(max_length=25)
    courses = models.ManyToManyField(Courses, through='StudentsCourses')

    def __str__(self):
        return self.name

class Roles(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return str(self.id)

class Users(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rol_id = models.ForeignKey(Roles, on_delete=models.CASCADE) 
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class StudentsCourses(models.Model):
    student = models.ForeignKey(Students, on_delete=models.CASCADE) 
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)

#modal with django

LineaIII/centro_educativo/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import Students, Users, Courses, StudentsCourses
from django.db.models import Q

def home(request):
    students_list = Students.objects.all()
    courses_list = Courses.objects.all()

    queryset = request.GET.get("buscar") #si existe?

    if queryset:
        students_list = Students.objects.filter(
            Q(code__icontains=queryset) |
            Q(name__icontains=queryset) |
            Q(lastName__icontains=queryset) 
        ).distinct()

    if(request.method == "POST"):
        try:
            if request.POST["courseCode"]:
                courseCode = request.POST["courseCode"]
                courseName = request.POST["courseName"]
                courseCredits = request.POST["courseCredits"]
                print(f"Codigo del curso: {courseCode, courseName, courseCredits}")

                newCourse = Courses(code=courseCode,name=courseName,credits=courseCredits)
                newCourse.save()
            else: pass
        except ValueError:
            print("Error")

    if(request.user.id):
        userid = request.user.id
        user_rol = Users.objects.get(pk=userid) 
        return render(request, "centro_educativo/home.html", {"students_list": students_list,"courses_list":courses_list, "user_rol":user_rol})
    else:
        return render(request, "centro_educativo/home.html")

def courses(request):
    courses_list = Courses.objects.all()

    queryset = request.GET.get("buscar") #si existe?

    if queryset:#if request.GET.get("buscar")
        courses_list = Courses.objects.filter(
            Q(code__icontains=queryset) |
            Q(name__icontains=queryset) |
            Q(credits__icontains=queryset) 
        ).distinct()

    if(request.method == "POST"):
        try:
            if request.POST["courseCode"]:
                courseCode = request.POST["courseCode"]
                courseName = request.POST["courseName"]
                courseCredits = request.POST["courseCredits"]
                print(f"Codigo del curso: {courseCode, courseName, courseCredits}")

                newCourse = Courses(code=courseCode,name=courseName,credits=courseCredits)
                newCourse.save()
            else: pass
        except ValueError:
            print("Error")

    if(request.user.id):
        userid = request.user.id
        user_rol = Users.objects.get(pk=userid) 
        return render(request, "centro_educativo/courses.html", {"courses_list": courses_list, "user_rol":user_rol})
    else:
        return render(request, "centro_educativo/courses.html")

#eliminar?
def studentForm(request):
    if(request.method == "POST"):
        if request.POST["studentCode"]:
            code = request.POST["studentCode"]
            name = request.POST["studentName"]
            lastName = request.POST["studentLastName"]
            newStudent = Students(code=code,name=name,lastName=lastName)
            newStudent.save()

    return redirect('/home')

def editStudent(request,student_id):
    courses_list = Courses.objects.all()
    student = Students.objects.filter(id=student_id).first()
    student_courses = StudentsCourses.objects.filter(student=student_id) 
    data = {
        'title' : 'Edición del alumno',
        'student' :  student,
        "courses_list": courses_list,
        'student_courses': student_courses
    }

    return render(request, "centro_educativo/editStudent.html", data)

def editRecordStudent(request):
    if(request.method == "POST"):
        if request.POST["studentCode"]:
            id = request.POST["id"]
            code = request.POST["studentCode"]
            name = request.POST["studentName"]
            lastName = request.POST["studentLastName"]
            student = Students.objects.get(id=id)
            student.name = name
            student.code = code
            student.lastName = lastName
            student.save()

    return redirect('/home')

def addCourseinUser(request, student_id, course_id):
    if student_id:
        #print(f"testeo:{student_id}/{course_id}")#agregar esto a la tabla intermedia
        student = Students.objects.filter(id=student_id).first()
        course = Courses.objects.filter(id=course_id).first()
        newStudentsCourses = StudentsCourses(student=student,course=course)
        newStudentsCourses.save()
        #return redirect(f'/editStudent/{student_id}')
        return redirect('/home')
    else:
        return redirect('/home')

def editCourse(request,course_id):
    course = Courses.objects.filter(id=course_id).first()
    course_students = StudentsCourses.objects.filter(course=course_id)
    data = {
        'title' : 'Edición del curso',
        'course' :  course,
        'course_students': course_students
    }

    return render(request, "centro_educativo/editCourse.html", data)

def editRecordCourse(request):
    if(request.method == "POST"):
        if request.POST["courseCode"]:
            id = request.POST["id"]
            code = request.POST["courseCode"]
            name = request.POST["courseName"]
            credits = request.POST["courseCredits"]
            course = Courses.objects.get(id=id)
            course.name = name
            course.code = code
            course.credits = credits
            course.save()

            return redirect('/courses')

def deleteStudent(request, pk):
    if(pk != ""):
        try:
            """ delStudent = get_object_or_404(Students, pk) """#Revisar
            delStudent = Students.objects.get(pk=pk)
            delStudent.delete()
        except ValueError:
            print(ValueError)

    return redirect('/home')

def deleteCourse(request, pk):
    if(pk != ""):
        try:
            delStudent = Courses.objects.get(pk=pk)
            delStudent.delete()
        except ValueError:
            print(ValueError)

    return redirect('/courses')

def not_found_page(request,exception):
    return render(request,"centro_educativo/404.html",{})

LineaIII/centro_educativo/templates/centro_educativo/courses.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Home</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    </head>
    <body class="bg-dark">
    {% if request.user.is_authenticated %}
        <div class="row justify-content-center align-items-center vh-100">
            <div class="col-9 bg-light border border-primary rounded">
                <div class="row top-user">
                    <div class="col users"><p class="user bg-dark">Cursos</p></div>
                    <div class="col">
                        <div class="container-fluid">
                            <form class="d-flex" role="search">
                                <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search" name="buscar">
                                <button class="btn btn-outline-success" type="submit"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                                    <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                                </svg></button>
                            </form>
                        </div>
                    </div>
                    <div class="col">                  
                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                            {% if user_rol.id == 1%}
                                <button type="button" class="btn btn-success float-end btn-block buttons_home" data-bs-toggle="modal" data-bs-target="#Course">
                                    Crear Curso
                                </button>                 
                                <!-- Modal Course -->
                                <div class="modal fade" id="Course" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                        <h5 class="modal-title" id="staticBackdropLabel">Registro de Curso</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        {% comment %} formulario {% endcomment %}
                                        <form method="POST">
                                            {% csrf_token %}
                                            <div class="modal-body">
                                                <div class="mb-3">
                                                  <label for="exampleInputEmail1" class="form-label">Codigo del Curso</label>
                                                  <input type="text" class="form-control" name="courseCode" required>
                                                </div>
                                                <div class="mb-3">
                                                  <label for="exampleInputPassword1" class="form-label">Nombre del curso</label>
                                                  <input type="text" class="form-control" name="courseName" required>
                                                </div>
                                                <div class="mb-3">
                                                    <label for="exampleInputPassword1" class="form-label">Creditos de curso</label>
                                                    <input type="number" class="form-control" name="courseCredits" required>
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                                                <button type="submit" class="btn btn-primary">Enviar</button>
                                            </div>
                                        </form>
                                    </div>
                                    </div>
                                </div>
                                <!-- Modal Student -->
                                <div class="modal fade" id="student" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                    <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                        <h5 class="modal-title" id="staticBackdropLabel">Registro de Alumno</h5>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        {% comment %} formulario {% endcomment %}
                                        <form method="POST" action="/studentForm">
                                            {% csrf_token %}
                                            <div class="modal-body">
                                                <div class="mb-3">
                                                  <label for="exampleInputEmail1" class="form-label">Codigo del Alumno</label>
                                                  <input type="text" class="form-control" name="studentCode" required>
                                                </div>
                                                <div class="mb-3">
                                                  <label for="exampleInputPassword1" class="form-label">Nombre del Alumno</label>
                                                  <input type="text" class="form-control" name="studentName" required>
                                                </div>
                                                <div class="mb-3">
                                                    <label for="exampleInputPassword1" class="form-label">Apellido del Alumno </label>
                                                    <input type="text" class="form-control" name="studentLastName" required>
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                                                <button type="submit" class="btn btn-primary">Enviar</button>
                                            </div>
                                        </form>
                                    </div>
                                    </div>
                                </div>
                            {% endif %}
                            <a class="btn btn-danger float-end btn-block buttons_home" href="{% url 'centro_educativo:logout' %}">Salir</a>
                        </div>
                    </div>
                 
                </div>
                <div class="table-responsive">
                    <table class="table">
                        <thead class="table-dark">
                            <tr>
                                <td>Codigo</td>
                                <td>Nombre</td>
                                <td>Creditos</td>
                                {% if user_rol.id == 1%}
                                    <td>Opciones</td>
                                {% endif %}
                            </tr>
                        </thead>
                        {% if courses_list %}
                        <tbody>
                            {% for course in courses_list %}
                                <tr>
                                    <td id="courseCode">{{course.code}}</td>
                                    <td>{{course.name}}</td>
                                    <td>{{course.credits}}</td>
                                    {% if user_rol.id == 1%}
                                        <td>
                                            <button type="button" class="btn btn-success float-end btn-block buttons_home">
                                                <a href="{% url 'centro_educativo:editCourse' course.id %}">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                                                        <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/>
                                                    </svg>
                                                </a>
                                            </button>
                                            {% comment %} borrar curso {% endcomment %}
                                            <button type="button" class="btn btn-danger float-end btn-block buttons_home edit">
                                                <a href="{% url 'centro_educativo:deleteCourse' course.id %}">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                                                        <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                                        <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                                    </svg>
                                                </a>
                                            </button>  
                                        </td>
                                        <!-- Modal Student Information -->
                                        <div class="modal fade" id="studentInfo" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                            <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                <h5 class="modal-title" id="staticBackdropLabel">Datos del Alumno</h5>
                                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                                </div>
                                                <div class="modal-body">
                                                    <div class="mb-3">
                                                    <label for="exampleInputEmail1" class="form-label">Codigo del Alumno</label>
                                                    <input type="text" id="studentCode"/>
                                                    </div>
                                                    <div class="mb-3">
                                                    <label for="exampleInputPassword1" class="form-label">Nombre del Alumno</label>
                                                    </div>
                                                    <div class="mb-3">
                                                        <label for="exampleInputPassword1" class="form-label">Apellido del Alumno </label>
                                                    </div>
                                                </div>
                                            </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        </tbody>
                        {% endif %}
                    </table>
                </div>
            </div>
        </div>  
    {% else %}
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-3 bg-light border border-primary rounded">
            <p>Logueate antes de interactuar en la pagina :D</p>
            <center>
                <a class="btn btn-danger btn-block" href="{% url 'centro_educativo:login' %}">Volver</a>
            </center>
        </div>
    </div>
    {% endif %}
    <script src="{% static 'student.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    </body>
</html>

LineaIII/centro_educativo/templates/centro_educativo/editCourse.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Home</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    </head>
    <body class="bg-dark">
    {% if request.user.is_authenticated %}
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-9 bg-light border border-primary rounded">
            <div class="row top-user">
                {% if course %}
                <form method="POST" action="/editRecordCourse">
                    {% csrf_token %}
                    <input type="hidden" value="{{course.id}}" name="id">
                    <div class="modal-body">
                        <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Codigo del Curso</label>
                        <input type="text" class="form-control" value="{{course.code}}" name="courseCode" required>
                        </div>
                        <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Nombre del curso</label>
                        <input type="text" class="form-control" value="{{course.name}}" name="courseName" required>
                        </div>
                        <div class="mb-3">
                            <label for="exampleInputPassword1" class="form-label">Creditos de curso</label>
                            <input type="number" class="form-control" value="{{course.credits}}" name="courseCredits" required>
                        </div>
                    </div>  
                    <div class="modal-footer">
                        <a class="btn btn-danger" href="{% url 'centro_educativo:courses' %}">Volver</a>
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </form>
                <div class="mb-3">
                    <b><label for="exampleInputPassword1" class="form-label">Reporte de alumnos en el curso</label></b>
                    {% if course_students %}
                        {% for student in course_students %}
                            <p>{{student.student.name}}</p>
                        {% endfor %}
                    {% endif %}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    {% else %}
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-3 bg-light border border-primary rounded">
            <p>Logueate antes de interactuar en la pagina :D</p>
            <center>
                <a class="btn btn-danger btn-block" href="{% url 'centro_educativo:login' %}">Volver</a>
            </center>
        </div>
    </div>
    {% endif %}
    <script src="{% static 'student.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    </body>
</html>

LineaIII/centro_educativo/templates/centro_educativo/editStudent.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Home</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
    </head>
    <body class="bg-dark">
    {% if request.user.is_authenticated %}
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-9 bg-light border border-primary rounded">
            <div class="row top-user">
                {% if student %}
                <form method="POST" action="/editRecordStudent">
                    {% csrf_token %}
                    <input type="hidden" value="{{student.id}}" name="id">
                    <div class="modal-body">
                        <div class="mb-3">
                        <label for="exampleInputEmail1" class="form-label">Codigo del Alumno</label>
                        <input type="text" class="form-control" value="{{student.code}}" name="studentCode" required>
                        </div>
                        <div class="mb-3">
                        <label for="exampleInputPassword1" class="form-label">Nombre del Alumno</label>
                        <input type="text" class="form-control" value="{{student.name}}" name="studentName" required>
                        </div>
                        <div class="mb-3">
                            <label for="exampleInputPassword1" class="form-label">Apellidos del Alumno</label>
                            <input type="text" class="form-control" value="{{student.lastName}}" name="studentLastName" required>
                        </div>
                        {% if student_courses %}
                            <div class="mb-3">
                                <label for="exampleInputPassword1" class="form-label">Cursos del Alumno</label>
                                {% for course in student_courses %}
                                    <p>{{course.course.name}}</p>
                                {% endfor %}
                            </div>
                        {% endif %}
                        {% if courses_list %}
                            <table class="table">
                                <thead class="table-dark">
                                    <tr>
                                        <td>Codigo</td>
                                        <td>Nombre</td>
                                        <td>Creditos</td>
                                        <td>Opción</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for course in courses_list %}
                                        <tr>
                                            <td id="courseCode">{{course.code}}</td>
                                            <td>{{course.name}}</td>
                                            <td>{{course.credits}}</td>
                                            <td>
                                                <button type="button" class="btn btn-primary">
                                                    <a href="{% url 'centro_educativo:addCourseinUser' student.id course.id %}">
                                                        Agregar
                                                    </a>
                                                </button>
                                      
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        {% endif %}
                    </div>  
                    <div class="modal-footer">
                        <a class="btn btn-danger" href="{% url 'centro_educativo:home' %}">Volver</a>
                        <button type="submit" class="btn btn-primary">Enviar</button>
                    </div>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
    {% else %}
    <div class="row justify-content-center align-items-center vh-100">
        <div class="col-3 bg-light border border-primary rounded">
            <p>Logueate antes de interactuar en la pagina :D</p>
            <center>
                <a class="btn btn-danger btn-block" href="{% url 'centro_educativo:login' %}">Volver</a>
            </center>
        </div>
    </div>
    {% endif %}
    <script src="{% static 'student.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    </body>
</html>